apiVersion: v1
kind: Service
metadata:
  name: pet-classification-api
  namespace: pet-adoptation
  labels:
    app: pet-classification-api
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  selector:
    app: pet-classification-api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  sessionAffinity: ClientIP
