apiVersion: v1
kind: Service
metadata:
  name: pet-adoptation-api
  namespace: pet-adoptation
  labels:
    app: pet-adoptation-api
spec:
  type: NodePort
  selector:
    app: pet-adoptation-api
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 8585
    protocol: TCP
    name: http
  sessionAffinity: ClientIP
